In [1]:
from collections import deque


coll = deque(maxlen=5)
for i in range(6):
    coll.append(i)
coll

deque([1, 2, 3, 4, 5])

In [5]:
import numpy as np
np.asarray(coll, dtype=np.float32).mean()

3.0

In [12]:
np.zeros(shape=25)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
arr = np.array([[1, 2, 3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.transpose(arr)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
np.rot90(np.fliplr(arr))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])